#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

rm -fr ${FOAM_USER_LIBBIN}/lib*.dylib
rm -fr ${FOAM_USER_LIBBIN}/lib*.so

set -x

./packages/Allwmake -j
./lib/Allwmake -j
./solver/Allwmake -j


# ----------------------------------------------------------------- end-of-file
